export default [
      {
        key: '1',
        name: 'test()',
        address: '原型方法'
      }, {
        key: '2',
        name: 'DOM.test()',
        address: '静态方法'
      }, {
        key: '3',
        name: 'test',
        address: '原型属性'
      }, {
        key: '4',
        name: 'DOM.test',
        address: '静态属性'
      }, {
        key: '5',
        name: 'test{}',
        address: '对象'
      }, {
        key: '6',
        name: 'DOM',
        address: '类型'
      }, {
        key: '7',
        name: 'DOM',
        address: '归类'
      }, {
        key: '8',
        name: '<test>',
        address: '其他'
      },{
        key: '1',
        name: 'test()',
        address: '原型方法'
      }, {
        key: '2',
        name: 'DOM.test()',
        address: '静态方法'
      }, {
        key: '3',
        name: 'test',
        address: '原型属性'
      }, {
        key: '4',
        name: 'DOM.test',
        address: '静态属性'
      }, {
        key: '5',
        name: 'test{}',
        address: '对象'
      }, {
        key: '6',
        name: 'DOM',
        address: '类型'
      }, {
        key: '7',
        name: 'DOM',
        address: '归类'
      }, {
        key: '8',
        name: '<test>',
        address: '其他'
      }
    ];